import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";

const NunitoFont = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${NunitoFont.className}`}>{children}</body>
    </html>
  );
}
